defaults:
  - model_checkpoint
  - model_summary
  - lr_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch}-step_{step}"
  monitor: "step"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: 1
