_target_: src.energies.multi_double_well_energy.MultiDoubleWellEnergy
name: dw4
dim: ${dim}
n_particles: ${n_particles}

data_from_efm: true
data_path: "data/test_split_DW4.npy"
data_path_train: "data/train_split_DW4.npy"
data_path_val: "data/val_split_DW4.npy"
data_path_test: "data/test_split_DW4.npy"

plot_samples_epoch_period: 1
data_normalization_factor: 1.0
is_molecule: true