_target_: src.energies.dist_energy.DistEnergy

dist:
  _target_: src.energies.dist_utils.GMM
  dim: ${dim}
  example: ${gmm_target} # heart, dist, fab, multi, grid, circle
  n_reference_samples: 1000000
